### ISSUE TITLE
[1.10.2] End Metals 1.2.0-beta2 wants Forge 12.18.3.2185

### ISSUE THREAD

**Issue by ACGaming** [MinecraftModDevelopment/EndMetals#29]
It seems that End Metals can't run with any Forge version newer than 12.18.3.2185.
Is this intentional? Forge 12.18.3.2511 is the latest release and should be safe to use.

**Comment by dshadowwolf** [comment]
Allowing for an older version is an issue ? Not seeing a problem here, please explain.

**Comment by jriwanek** [comment]
@ACGaming Do you mean it refuses to load on any version later than that?

**Comment by ACGaming** [comment]
@jriwanek Exactly.

**Comment by dshadowwolf** [comment]
hrm... that sounds like someone left off a comma in the @Mod annotation, but it exists in the current source so I can't say

**Comment by spiral6** [comment]
Can confirm, having this issue as well. 
```
[01:58:36] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.MissingModsException: Mod endmetals (End Metals) requires [forge@[12.18.3.2185,)]
Missing Mods:
        forge : [12.18.3.2185,)


        at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266) ~[Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:536) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141-1-ojdkbuild]
```

**Comment by jriwanek** [comment]
It's a bug related to a capital F in forge instead of a lowercase F, I'll be pushing updates for the whole lot soon enough, please be patient in the mean time

**Comment by Boomflex** [comment]
Hi there @jriwanek any estimated time on this as we are looking to make an update to All the Mods 1.10.2 and would love to get this up to date.

Thanks.

**Comment by jriwanek** [comment]
As soon as I've got the backports finished.
(I'd say tenatively no more than a week now)

**Comment by ntman4real** [comment]
+1

**Comment by jriwanek** [comment]
@Boomflex Still running a bit late, but I'm digging in hard now, @ACGaming's report led to me actually breaking things in the way he said were broken, so, I'll be reverting that, I don't blame @spiral6 however, as he likely downloaded the "fixed" version, which tbh as I checked the back code, and couldn't find the issue that ACGaming reported in the code, was likely a false report, so, I'll be interested to see what comes of that.

**Comment by Travis9x** [comment]
I can confirm I'm having this same issue, with the latest (only?) version available in Twitch.  Mod will not load with any Forge version higher than 12.18.3.2185

**Comment by jriwanek** [comment]
Try the beta2 version (one earlier) the beta 3 was with the incorrect fix applied.

**Comment by Joly0** [comment]
Is this going to be fixed some day? i am trying to play with the EndMetals-1.12-1.2.0-beta2.29 version and this error still exists

**Comment by jriwanek** [comment]
beta2 is ancient, beta4 is already out, update.

**Comment by Joly0** [comment]
I know that, but i dont want to play on 1.12. I want to play on 1.10.2 so i need an older Version and its really sad, that the whole mod doesnt work for this Version

**Comment by jriwanek** [comment]
```i am trying to play with the EndMetals-1.12-1.2.0-beta2.29```
If you're gonna say 1.12, I'm gonna assume you mean 1.12.
New versions for 1.10.x and 1.11.x are coming.

**Comment by Joly0** [comment]
If this Issue is created for the 1.10.2 i assume you gonna understand, that i mean the 1.10.2.

It cant do anything against it, that the Version with the name EndMetals-1.12-1.2.0-beta2.29 is for 1.10, 1.11 and 1.12 but nvm.

Good to know, that a fixed Version is going to come

**Comment by jriwanek** [comment]
I see, we've got some mistagged files, thanks for the heads up, I'll have to reprocess and correctly tag.
